### PR TITLE
CMake integration.

### PR DESCRIPTION
**Pull request by fghoussen**
CMake integration + compilation fix (KO on debian-based distros).
The PR comes with github Continuous Integration.

### CODE REVIEW

**Comment by fghoussen** [comment]
If you're open to this move, let me know. If so, it's easy to add install/pkg file too to ease distribution/releases.

**Comment by GillesDebunne** [comment]
Thanks a lot for this contribution. Leveraging GitHub actions will help improve the quality of the library.

**Comment by fghoussen** [comment]
> Thanks a lot for this contribution. Leveraging GitHub actions will help improve the quality of the library.

Avec plaisir ! :)

**Comment by GillesDebunne** [comment]
😁

**Pull request merged**
